version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    env_file:
      - .env
    volumes:
      - .:/var/www
    networks:
      - app-network
    expose:
      - "9000"  # Expose le port 9000 pour PHP-FPM, mais ne l'expose pas à l'extérieur

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"  # Assure-toi que le port 80 de Nginx est exposé
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
