version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    env_file:
      - .env
    volumes:
      - .:/var/www
    networks:
      - app-network  # Assure-toi que le service app est sur le bon réseau

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"  # Expose le port 80 de Nginx sur le port 8000 de l'hôte
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network  # Assure-toi que le service nginx est aussi sur le même réseau

networks:
  app-network:
    driver: bridge  # Utilisation du réseau bridge pour permettre la communication entre les conteneurs
